### ISSUE TITLE
how to set break after 30 mins for 5 mins on loop everyday 

### ISSUE THREAD

**Issue by TecnikOfficial** [GChristensen/retreat#2]
i dont want disable for 1 hr pls help 
![image](https://github.com/GChristensen/retreat/assets/44696073/a6bf11db-6e4d-4e34-83cd-fc945177b527)

**Comment by GChristensen** [comment]
The ability to disable for a fixed amount of time was made intentionally. This would not be changed. The only workaround is to close application completely.
You may also type 24 there or more.

**Comment by TecnikOfficial** [comment]
if i set 24hr ... it will mean tht once every 24 i will have  5 mins break

**Comment by GChristensen** [comment]
In the bottom left of the settings window there is a tiny help link. 
The "Disable" setting is the time for which the app is disabled from the tray context menu.
To break after 30 mins set break for 5 min. and period for 35 min.

**Comment by TecnikOfficial** [comment]
i did tht once after 30 min i got break for 5 min but again after 30 min i didnt got break

**Comment by GChristensen** [comment]
OK, I'll tests this.

**Comment by TecnikOfficial** [comment]
thx ,,.. btw i like this app its lite on sys resources and has more features then other apps ... nice work

**Comment by GChristensen** [comment]
Can not reproduce this, it works as expected. If you set period duration to 35 min, the break time will not align with the beginning of a hour, because every time 5 min will be added to the assumed start time.
If you need the breaks to be aligned with the beginning of the current hour, it is necessary to set the period duration to 30 min, but the break will take pace every 25 min.

**Comment by TecnikOfficial** [comment]
oh it worked now thx ... i think disable for (hrs) means disable after (hrs) tht ws confusing for me now its ok
